### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by bennuttall** [piwheels/piwheels#16]
It would be nice if we could provide some information via an API - nothing fancy, just some static JSON generated from the DB.

Either one big JSON blob containing everything, or perhaps a few more distinct sets of data.

I'm thinking:

- List of packages (could be limited to those we have available, or contain metadata including success / build output
- List of versions per package
- Build output

**Comment by waveform80** [comment]
This should be relatively simple - should probably go in the index_scribe task (which deals with re-writing the index.html files whenever new files are transferred).

**Comment by bennuttall** [comment]
Ok, another idea: we could do what PyPI does and provide a nicer looking HTML view of the index as well as `/simple/`. PyPI packages are browsable at `/pypi/` (ours could be `/piwheels/`) and JSON data about the package is available at `/pypi/{package}/json` e.g. https://pypi.python.org/pypi/gpiozero/json

So we could provide a simple browsable front-end and JSON API for packages e.g. https://www.piwheels.hostedpi.com/piwheels/numpy/ and https://www.piwheels.hostedpi.com/piwheels/numpy/json

Obviously these pages would be statically generated when builds occur, but maybe this would be a nice way of providing an interface. It could list simple stats on the package page, like number of files available, maybe list them, that kind of thing, and provide a link to the JSON data.

**Comment by lyw07** [comment]
Hi! I'm wondering if this api is still under development and will be available in the near future. Thank you!

**Comment by bennuttall** [comment]
No work has been done on this so far, but I'd be interested to know what features you'd be looking for.

**Comment by bennuttall** [comment]
In progress in the JSON branch!
