### ISSUE TITLE
Fix package related issues links on package pages

### ISSUE THREAD

**Issue by flit** [piwheels/piwheels#192]
Issues for packages are now tracked in piwheels/packages. But the links at the bottom of package pages (under "Issues with this package?", "Package/version missing?", "Package broken?") for searching and creating new issues still link to the main piwheels project issue tracker.

**Comment by bennuttall** [comment]
Addressed in 63a4e4a55864db5ef5c59a8c5e067bb1e69dd62e but not deployed to piwheels.org yet - the links go to issues here but the issue templates refer people to the new location.
