### ISSUE TITLE
Interest in Nvidia Jetson

### ISSUE THREAD

**Issue by seanfarley** [piwheels/piwheels#196]
I just found this repo (very cool!) and I was wondering if there was any interest in providing wheels for platforms like the Nvidia Jetson Nano. No worries if that's outside the scope of this project; just wanted to see what the options were. Thanks!

**Comment by bennuttall** [comment]
We wouldn't do that but the project is open source, so you can run your own instance if you want. We run piwheels.org from a Raspberry Pi, but the master can be any server. We have the DB on a VM, and obviously the builders themselves are Pis. You can kind the documentation at https://piwheels.readthedocs.io

**Comment by seanfarley** [comment]
No worries! Thanks for the kind response :-)
