### ISSUE TITLE
Index should have flags indicating python 3 only libraries

### ISSUE THREAD

**Issue by hmaarrfk** [piwheels/piwheels#202]
We had issues where users reported having trouble troubling installing scikit-image on a raspberrypi and python 2.

I tracked it down to the fact that we have recently recently a python 3 only package, and that piwheels doesn't seem to include that information in the metadata

See debugging history here
https://github.com/scikit-image/scikit-image/issues/4094#issuecomment-522243575

The issue can be recreated on your local x86 computer by running the two commands:
```
pip install --extra-index-url https://www.piwheels.org/simple scikit-image
```
which will find the 0.15 version attempt to download it and compile it from source. On PyPi, this version is flagged as Python 3 only, and will not be downloaded by `pip2`.

I don't think the user ever reported it, but I feel like this might become an increasing source of friction as more packages, even pure python ones, move to python 3 only and thus will not be installable because of missing metadata.

Not sure how to fix this, but figured I would report it.

I hope this helps.

**Comment by bennuttall** [comment]
That's weird. It looks like an issue with networkx. They provide sdist on PyPI, which has >=Py3.5 in the metadata. Then piwheels builds a wheel of it, and it gets tagged as `py2.py3` which isn't the default. It must be specified by networkx that their package is (or was) universal. I'll look into it.

**Comment by hmaarrfk** [comment]
oh you are right, it is just networkx. It could be that they made a mistake in their first release, and pulled a package???

Used to list the wheel as universal
https://github.com/networkx/networkx/blob/networkx-2.3/setup.cfg

On master they removed the label
https://github.com/networkx/networkx/blob/master/setup.cfg

https://github.com/networkx/networkx/pull/3465

I guess this is a package issue, and not an index issue. :/

**Comment by bennuttall** [comment]
Ok I've removed the 2.3 versions of that package, should be ok from now on though.

Thanks for reporting!
