### ISSUE TITLE
opencv_python armv8 

### ISSUE THREAD

**Issue by redparck** [piwheels/piwheels#207]
This package needs to be installed on pi4. Is there an adaptation plan?

**Comment by bennuttall** [comment]
We don't build armv8/aarch64 wheels. What OS are you using?

**Comment by redparck** [comment]
I am using jeston nano and its cpu is ARMV8

**Comment by bennuttall** [comment]
> This package needs to be installed on pi4

> I am using jeston nano

¯\_(ツ)_/¯
