### ISSUE TITLE
test Piwheels with pip 20.1b1

### ISSUE THREAD

**Issue by brainwane** [piwheels/piwheels#213]
Hi! [Here's the announcement](https://mail.python.org/archives/list/python-announce-list@python.org/thread/3BU3T7TGYJCBRRJ4WRJL3PMMJKCESNFK/) of the beta release of a new version of pip, pip 20.1b1. Could you try testing it out with piwheels to check whether stuff breaks? If so [please let us know](https://github.com/pypa/pip/issues/). We're hoping to release pip 20.1.0 around Tuesday 28 April. Thanks!

**Comment by bennuttall** [comment]
Sorry not to have provided any feedback before release - I did test and didn't come up with anything, and we're using 20.1 now 👍

**Comment by brainwane** [comment]
Thanks @bennuttall. Sometime in June we'll probably be releasing another beta that we'd love help testing -- is it ok to open a fresh issue here at that time to request that?

**Comment by bennuttall** [comment]
Yes, please do
