### ISSUE TITLE
Error: cant uninstall "pyzmq"

### ISSUE THREAD

**Issue by Nerijusas** [piwheels/piwheels#246]
https://pastebin.com/wWtPM9F3

**ERROR: Cannot uninstall 'pyzmq'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

**Comment by bennuttall** [comment]
This is the wrong place for package issues, and this isn't actually an issue with piwheels.

You need to remove the debian package `python3-zmq` before installing `pyzmq` with pip.
