### ISSUE TITLE
Canonicalise package names

### ISSUE THREAD

**Issue by bennuttall** [piwheels/piwheels#252]
Since packages can be created, deleted, re-created, have versions released, etc all with the same package name in different forms, we need a solution that meets the following criteria:

- canonical form is written to `/simple/pkg`
- canonical form is written to `/project/pkg`
- symlinks created for any non-canonical forms seen, pointed at the canonical form project dir (not required for simple)

So if the following happens:

- Package `foo.bar` created
- `foo.bar` v1.0 released
- `foo-bar` v1.1 released
- `Foo_Bar` v1.2 released

The following dirs and symlinks should be created:

- `/simple/foo-bar` (dir)
- `/project/foo-bar` (dir)
- `/project/foo.bar` (symlink)
- `/project/Foo_bar` (symlink)

Currently, we register a new package every time we see a new unique package string, create a directory for the seen form, and symlink to the canonical form (if different) for both simple indexes and project pages. But as we've run through PyPI's history we've ended up registering new packages when we've seen a package name in a new form. See #198.

I guess it's debatable a) which form we use as the title on project pages and b) whether we use the *most recently used* form (or the *first seen* or *last created*) as the default project page path, or just the canonical. The latter would be easier to manage, and would still work with symlinks. It's just a little inconsistent (with PyPI) and maybe it's *better* to use the *chosen* style of the package (e.g. "Flask" not "flask"). One possible option could be to query the JSON API (when we get the project description) and use whatever that contains as the "display" format.

This issue requires a) code changes and b) a script to reorganise the existing live indexes.

**Comment by bennuttall** [comment]
I think it's probably that whatever form the package was *created as* is what warehouse uses as the default on project pages. @di @ewdurbin @dstufft can anyone confirm?

**Comment by di** [comment]
PyPI allows users to rename their project (as long as it still canonicalizes to the same name) on every upload: https://github.com/pypa/warehouse/blob/8815e29f36c743e68b08e6abd40eed014748cbcc/warehouse/forklift/legacy.py#L1009-L1013

The default on the project pages is whatever the last release used.

**Comment by bennuttall** [comment]
Ok that's good to know. Thanks!
