### ISSUE TITLE
Expose logs for failed builds

### ISSUE THREAD

**Issue by graebm** [piwheels/piwheels#274]
I maintain a package ([awscrt](https://www.piwheels.org/project/awscrt/)) which is currently broken on piwheels. It would be helpful for package developers if the build logs where available (at least the logs for the most recent failure).

In the past I've been able to reproduce issues on my personal Raspberry Pi and put out a fix. But I haven't yet been able to reproduce the issue piwheels is having with the latest release (0.11.13). Having logs available could really help with the detective work.

Sorry for the feature request. piwheels is amazing. My mind was blown the first time I tried to test this package on a Rasberry Pi and got a precompiled wheel. I wish PyPI worked this way.

**Comment by bennuttall** [comment]
Have a look at issue #1 :)

**Comment by graebm** [comment]
Sorry for missing that. Public logs are the last planned feature that isn't done yet. Closing this issue...

**Comment by bennuttall** [comment]
No worries!

Some background:

Logs are stored in the database. That table is 89GB. The piwheels website is a static site, so pages (like a [project page](https://www.piwheels.org/project/awscrt/)) are written out as they change. If we were to also write out the output of every build, that would be an extra 89GB of contents (and growing).

If we were to make them available on request, that would require a dynamic handler - but piwheels is hosted on a Pi, so we're more comfortable with it serving static files than managing requests on top of everything else (like controlling all the other Pis building wheels).

However, neither option is beyond a possibility. As you can see from issue #1, it's something we'd like to do at some point.

What we tend to do is pastebin the output when a maintainer opens a package issue. If you hit the "new issue" button on your project's page, I'll do that for you.

**Comment by bennuttall** [comment]
Just checked - the sum of the capacity of wheels is 1.75TB so an extra 89GB isn't a huge increase tbh. What do you think @waveform80?

**Comment by graebm** [comment]
The most recent failed builds are the most interesting ones, so if you're going for a static maybe just included those and leave out the old and/or successful builds

**Comment by graebm** [comment]
I just noticed that logs are available! Thanks so much!
