### ISSUE TITLE
Per-distro index URLs

### ISSUE THREAD

**Issue by jack1142** [piwheels/piwheels#301]
Would it be possible to have per-distro indexes that would only show the wheels that are for that specific distro? Currently, having the extra index URL in `/etc/pip.conf` means that wheels for all Python versions, not just the ones meant for the Python version that was distributed with that specific OS.
This means that *if* one were to compile and install say, Python 3.9 on the current stable Raspberry Pi OS (which is based on Debian Buster), the Python 3.9 pip will gladly install wheels in piwheels index even though they are linked with libraries that are distributed with Bullseye, not Buster and therefore not work.
If there were a per-distro index URL, one could just set the buster one and not have Python 3.9 pip think that they are valid wheels for the distro while still having Python 3.7 pip see the wheels from piwheels.

**Comment by bennuttall** [comment]
Not possible, no. As per the homepage:

> Our wheels are only supported under 32-bit (armhf) Raspberry Pi OS, and only for the version of Python provided by each OS release

We can't be expected to build for multiple Python versions separately for each distro version. We provide Python 3.9 wheels and they work if you upgrade your OS to Bullseye. Just replace `buster` with `bullseye` in your apt sources and run `apt dist-upgrade`.

**Comment by jack1142** [comment]
> We can't be expected to build for multiple Python versions separately for each distro version

That's not what I'm asking. I'm asking for there to be index URLs that act as a filter - if you use `buster`-specific index URL, you would only see wheel built for 3.7 for example.

**Comment by bennuttall** [comment]
I don't understand how that would help

**Comment by jack1142** [comment]
This way, wheels would be provided only for the Python that was actually shipped with that specific distro - if the user has buster with the installed by default Python 3.7 (and is, therefore, the Python version that piwheels provides wheels for when it comes to buster) *and* Python 3.9 (that was not shipped with that distro and therefore must have been compiled/installed by the user on their own), the user could still just simply `python3.9 -m pip install package` without having to worry about pip installing non-compatible wheels (which is what happens when you do that on Raspberry Pi OS due to `/etc/pip.conf`).

**Comment by bennuttall** [comment]
In that case, piwheels is of no use to you. You'd be pointing to a Buster-only version of piwheels that only provides pure Python and cp37m wheels. You wouldn't accidentally download any cp39 Bullseye wheels, but you wouldn't gain anything else. You'd be better off just removing the piwheels config - or just upgrade to Bullseye and it's win/win.

**Comment by jack1142** [comment]
> You wouldn't accidentally download any cp39 Bullseye wheels, but you wouldn't gain anything else. 

I would still benefit from wheels when pip installing something for Python 3.7 and that is what I'm looking for. I want to benefit when installing something for Python 3.7 and at the same time I don't want issues with incompatible wheels when installing something for Python 3.9. I wanted that to be possible without having to use additional flags in either of these cases.

**Comment by bennuttall** [comment]
> I know that I can use a flag, I just think that I shouldn't need to.

You're asking us to do a significant amount of work, in order to avoid having to use a flag.
