### ISSUE TITLE
Hey the website is down

### ISSUE THREAD

**Issue by bwees** [piwheels/piwheels#307]
I just tried installing backtrader (as well as other packages) with pip today and I cannot access the piwheels site or get a package to download. Pip gives this error: `WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)'))': /simple/backtrader/`. The site when accessed timesout and gives a connection refused. CURLing https://www.piwheels.org produces nothing.

**Comment by bennuttall** [comment]
It was down for about an hour last night, looking into it

**Comment by caubut-charter** [comment]
@bennuttall Seems to be down again, same error.

**Comment by bennuttall** [comment]
Back now?

**Comment by caubut-charter** [comment]
@bennuttall yep, thanks!

**Comment by MrNaif2018** [comment]
@bennuttall Looks like the site is down again (seeing same messages in our CI logs)

**Comment by bennuttall** [comment]
Looks like there's an NFS issue with our host. Looking into it.
