### ISSUE TITLE
Cross platform download not working for MarkupSafe

### ISSUE THREAD

**Issue by mechsin** [piwheels/piwheels#324]
So I was looking through you FAQ and found the "How can I download all the wheels I need for an offline installation?" and follow the example exactly as typed targeting the package MarkupSafe however I don't seem to be getting the result I am suppose to. When I run 

`py -m pip download --extra-index-url https://www.piwheels.org/simple --implementation cp --platform linux_arm7l --abi cp37m --only-binary=:all: MarkupSafe`

It downloads `MarkupSafe-0.11-py3-none-any.whl` while I would expect it download `MarkupSafe-2.1.1-cp37-cp37m-linux_armv7l.whl`

I am running the download command on a Windows 10 machine using Python 3.10.1 and pip version 22.2.2

I need this of course because I have a Pi that is not normally online and pull updates when we they are required for our applications so I actually ran across this issue using a requirements file that requires 2.1.1. 

Am I doing something wrong or is this some kind of bug?

**Comment by bennuttall** [comment]
That's very strange.

I tried swapping `--abi cp37m` to `--python-version 3.7` and that worked.

Will do further investigation. Thanks for the heads up.

**Comment by bennuttall** [comment]
Adding `-vvv` (maximum verbose) shows the file `MarkupSafe-2.1.1-cp37-cp37m-linux_armv7l.whl` being skipped:

```
Skipping link: none of the wheel's tags (cp37-cp37m-linux_armv7l) are compatible (run pip debug --verbose to show compatible tags): https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.1.1-cp37-cp37m-linux_armv7l.whl#sha256=04ecce2077c9c531334c847b604835e8e909f73d1fe596ceae30c8046ca90686 (from https://www.piwheels.org/simple/markupsafe/) (requires-python:>=3.7)
```

But that doesn't exactly tell me why.

`pip download --help` says of the `--abi` option:

```
Only use wheels compatible with Python abi <abi>, e.g. 'pypy_41'. If not specified, then the current interpreter abi tag is used. Use this option multiple times to specify multiple abis supported by the target interpreter. Generally you will need to specify --implementation, --platform, and --python-version when using this option.
```

I think it suggests you generally need to also specify `--python-version`. That seemed to work for me, so it's probably worth either switching to or adding `--python-version` in the FAQ.

**Comment by mechsin** [comment]
Hmm I did the swap and it is still downloading `MarkupSafe-0.11-py3-none-any.whl` for me the command is below

`py -m pip download --extra-index-url https://www.piwheels.org/simple --implementation=cp --platform=linux_arm7l --python-version=3.7 --only-binary=:all: MarkupSafe`

Did I interpret your switch correctly?

**Comment by bennuttall** [comment]
Oh, you have been using the wrong `platform` value. It should be `linux_armv7l` not `linux_arm7l`.

But still, swapping `--abi cp37m` for `--python-version 3.7` makes a difference:

```console
(piptest) fern:~ $ pip download --extra-index-url https://www.piwheels.org/simple --implementation cp --platform linux_armv7l --abi cp37m --only-binary=:all: MarkupSafe
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting MarkupSafe
  File was already downloaded /home/ben/MarkupSafe-0.11-py3-none-any.whl
Successfully downloaded MarkupSafe
```

```console
(piptest) fern:~ $ pip download --extra-index-url https://www.piwheels.org/simple --implementation cp --platform linux_armv7l --python-version=3.7 --only-binary=:all: MarkupSafe
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting MarkupSafe
  File was already downloaded /home/ben/MarkupSafe-2.1.1-cp37-cp37m-linux_armv7l.whl
Successfully downloaded MarkupSafe
```

**Comment by mechsin** [comment]
Ok yeah I see. Still have to spell everything correctly. Once I fix the v everything works. Thanks for the second set of eyes.
