### ISSUE TITLE
How is the whl craeted in piwheels?

### ISSUE THREAD

**Issue by tropxy** [piwheels/piwheels#325]
Hi everyone,

First, thanks for the very valuable project that you guys started!

I have two targets for which I use piwheels: armv7 and aarch64.
I have a particular problem with cryptography as I wanted to use the most recent version of the lib, but this one uses now cargo/rust to compile the library to the target. This seems to not work well within Docker in an armv7 architecture: https://github.com/rust-lang/cargo/issues/8719

https://github.com/rust-lang/cargo/issues/7451

I have tried to build the container using some workarounds like the tmpfs one: https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/109

but didnt work for me...so I was curious how did you guys manage to build an armv7 whl for cryptogrpahy? did you use a native armv7 machine?

And is it possible you guys consider building images for aarch64 and also for python 3.10 and buster flavour?

Thanks!

**Comment by bennuttall** [comment]
https://piwheels.readthedocs.io/en/latest/

**Comment by tropxy** [comment]
thanks @bennuttall ;) 

Any thoughts on this one?
> And is it possible you guys consider building images for aarch64 and also for python 3.10 and buster flavour?

**Comment by bennuttall** [comment]
No - see:

- https://github.com/piwheels/packages/issues/119

Also see https://www.piwheels.org/faq.html

> Which Python versions does piwheels support?
> piwheels supports Python 3 only. While most packages available will work in any version of Python 3, some packages are only compatible with the minor version with which they were built. We build using for the ABI of the Python 3 version distributed with Debian releases:
>
>    Jessie - Python 3.4 (end of life)
>    Stretch - Python 3.5
>    Buster - Python 3.7
>    Bullseye - Python 3.9
