### ISSUE TITLE
Build more recent cryptography wheels through rust

### ISSUE THREAD

**Issue by gpongelli** [piwheels/piwheels#330]
Hi, 
first of all thanks for this awesome work!

I've recently faced issue when installing poetry on Pi due to cryptography package, that needs Rust to be compiled and in an emulated environment, used with Github CI, this cannot be solved.

I can access to piwheels to use your wheels and I've looked at [cryptography status here](https://www.piwheels.org/project/cryptography/) , but [v39 fails on python 3.9](https://www.piwheels.org/logs/0000/0929/0792.txt) (cryptography v39 seems to be [poetry's dependency](https://github.com/python-poetry/poetry/blob/master/poetry.lock#L404-L405)).

So I've setup my Pi manually installing rust compiler, and it builds with success, here are the steps I did:
- `curl https://sh.rustup.rs -sSf | sh -s -- -y`
- `rustc --version` actually reports
```
pi@rpi:~ $ rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)
```
- python3 is
```
pi@rpi:~ $ python3 --version
Python 3.9.2
```

- building via pip3 completes successfully:

```
pi@rpi:~ $ pip3 install cryptography==39.0.1
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cryptography==39.0.1
  Downloading cryptography-39.0.1.tar.gz (603 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 603.6/603.6 kB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography==39.0.1) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography==39.0.1) (2.21)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... done
  Created wheel for cryptography: filename=cryptography-39.0.1-cp39-cp39-linux_armv7l.whl size=1805553 sha256=b427d0f839ee4f61fa7e6b48ac20e95376e1b25436a9e8a2ac16b81e1e241199
  Stored in directory: /home/pi/.cache/pip/wheels/15/22/67/b032780b006e19889222b9010bad98d1e3e0085bb961b90f9c
Successfully built cryptography
Installing collected packages: cryptography
Successfully installed cryptography-39.0.1

```

Is it possible to install rust compiler on your slave machines, so those kind of packages can be correctly built and being available on piwheels ?

Thanks!

**Comment by bennuttall** [comment]
Have you seen #328?

**Comment by gpongelli** [comment]
> Have you seen #328?

Sorry, I've read it just now.
