### ISSUE TITLE
I use decompyle3 or uncompyle6 It decompiles my functions that do not start with "get" but if my function or method starts with "get" it generates an error?

### ISSUE THREAD

**Issue by guressemalenga** [piwheels/piwheels#345]
I use decompyle3 or uncompyle6
It decompiles my functions that do not start with "get" but if my function or method starts with "get" it generates an error:
def get_list_patientParse error at or near `POP_BLOCK' instruction at offset 120

so my function is get_list_patient(request):
since it starts with "get" it gives this error.

**Comment by bennuttall** [comment]
This is not the right place to report issues about decompyle3. Please contact the maintainers of the project.
